### PR TITLE
Download a platform-specific GPG archive on installation

### PR DESCRIPTION
**Pull request by smashwilson**
A regular `npm install` should drop an [atom/squeegpg-native](https://github.com/atom/squeegpg-native) archive for the current platform within this directory.

Lightly "inspired" by @shiftkey's [dugite](https://github.com/desktop/dugite/blob/master/script/download-git.js) work.

### CODE REVIEW

**Comment by shiftkey** [comment]
> Lightly "inspired" by @shiftkey's dugite work.



Does this make https://github.com/desktop/dugite-native/issues/36 less urgent now?

**Comment by smashwilson** [comment]
I hope so! My goal here is to get something we can share between atom/github and Desktop for GPG integration. The TypeScript half of things [has been started, too](https://github.com/atom/squeegpg).

Mind if I ping you for feedback on a PR when I get to the point where I'm hashing out the public API, to make sure it's something we can both use?  It'll likely be a _little_ more complicated than the `GitProcess` one because we have the GPG homedir and `gpg-agent` process to manage as well.

**Comment by smashwilson** [comment]
Oh, also, to address some of my concerns on that issue, apparently Git for Windows already bundles gpg 1.x. So...

**Comment by shiftkey** [comment]
> Mind if I ping you for feedback on a PR when I get to the point where I'm hashing out the public API, to make sure it's something we can both use?

Sure thing. I haven't really thought about our use case https://github.com/desktop/desktop/issues/78 much lately but this gives me time to catch up.

> Oh, also, to address some of my concerns on that issue, apparently Git for Windows already bundles gpg 1.x. So...

It does? Rad, I'll confirm that it's also in MinGit and update that issue...

**Comment by smashwilson** [comment]
👍 No rush - I know this isn't on your roadmap any time soon. Mostly I want to make sure (a) you're vaguely aware I'm doing this and (b) I don't box myself into an Atom-shaped corner somehow.

Also, there's certainly a `gpg` binary in my git install that I don't recall putting there myself:

git-gpg

We should _probably_ still check with legal, at least about licensing issues?

**Comment by shiftkey** [comment]
> Also, there's certainly a `gpg` binary in my git install that I don't recall putting there myself:

That's the full version of Git for Windows - MinGit has a bunch of tools removed that aren't important when embedding Git into apps, and here's what we ship in `dugite` currently:

```shellsession
$ find app/node_modules/dugite/git/usr/bin
app/node_modules/dugite/git/usr/bin
app/node_modules/dugite/git/usr/bin/awk.exe
app/node_modules/dugite/git/usr/bin/b2sum.exe
app/node_modules/dugite/git/usr/bin/basename.exe
app/node_modules/dugite/git/usr/bin/cat.exe
app/node_modules/dugite/git/usr/bin/comm.exe
app/node_modules/dugite/git/usr/bin/cp.exe
app/node_modules/dugite/git/usr/bin/cut.exe
app/node_modules/dugite/git/usr/bin/dash.exe
app/node_modules/dugite/git/usr/bin/date.exe
app/node_modules/dugite/git/usr/bin/dirname.exe
app/node_modules/dugite/git/usr/bin/echo.exe
app/node_modules/dugite/git/usr/bin/env.exe
app/node_modules/dugite/git/usr/bin/expr.exe
app/node_modules/dugite/git/usr/bin/false.exe
app/node_modules/dugite/git/usr/bin/find.exe
app/node_modules/dugite/git/usr/bin/getfacl.exe
app/node_modules/dugite/git/usr/bin/getopt.exe
app/node_modules/dugite/git/usr/bin/grep.exe
app/node_modules/dugite/git/usr/bin/head.exe
app/node_modules/dugite/git/usr/bin/ls.exe
app/node_modules/dugite/git/usr/bin/mkdir.exe
app/node_modules/dugite/git/usr/bin/mktemp.exe
app/node_modules/dugite/git/usr/bin/msys-2.0.dll
app/node_modules/dugite/git/usr/bin/msys-asn1-8.dll
app/node_modules/dugite/git/usr/bin/msys-com_err-1.dll
app/node_modules/dugite/git/usr/bin/msys-crypt-0.dll
app/node_modules/dugite/git/usr/bin/msys-crypto-1.0.0.dll
app/node_modules/dugite/git/usr/bin/msys-gcc_s-seh-1.dll
app/node_modules/dugite/git/usr/bin/msys-gmp-10.dll
app/node_modules/dugite/git/usr/bin/msys-gssapi-3.dll
app/node_modules/dugite/git/usr/bin/msys-heimbase-1.dll
app/node_modules/dugite/git/usr/bin/msys-heimntlm-0.dll
app/node_modules/dugite/git/usr/bin/msys-history7.dll
app/node_modules/dugite/git/usr/bin/msys-hx509-5.dll
app/node_modules/dugite/git/usr/bin/msys-iconv-2.dll
app/node_modules/dugite/git/usr/bin/msys-intl-8.dll
app/node_modules/dugite/git/usr/bin/msys-krb5-26.dll
app/node_modules/dugite/git/usr/bin/msys-mpfr-4.dll
app/node_modules/dugite/git/usr/bin/msys-ncursesw6.dll
app/node_modules/dugite/git/usr/bin/msys-pcre-1.dll
app/node_modules/dugite/git/usr/bin/msys-readline7.dll
app/node_modules/dugite/git/usr/bin/msys-roken-18.dll
app/node_modules/dugite/git/usr/bin/msys-sqlite3-0.dll
app/node_modules/dugite/git/usr/bin/msys-ssl-1.0.0.dll
app/node_modules/dugite/git/usr/bin/msys-ssp-0.dll
app/node_modules/dugite/git/usr/bin/msys-wind-0.dll
app/node_modules/dugite/git/usr/bin/msys-z.dll
app/node_modules/dugite/git/usr/bin/mv.exe
app/node_modules/dugite/git/usr/bin/pathchk.exe
app/node_modules/dugite/git/usr/bin/printf.exe
app/node_modules/dugite/git/usr/bin/pwd.exe
app/node_modules/dugite/git/usr/bin/readlink.exe
app/node_modules/dugite/git/usr/bin/rebase.exe
app/node_modules/dugite/git/usr/bin/rebaseall
app/node_modules/dugite/git/usr/bin/rm.exe
app/node_modules/dugite/git/usr/bin/rmdir.exe
app/node_modules/dugite/git/usr/bin/sed.exe
app/node_modules/dugite/git/usr/bin/sh.exe
app/node_modules/dugite/git/usr/bin/sort.exe
app/node_modules/dugite/git/usr/bin/ssh-add.exe
app/node_modules/dugite/git/usr/bin/ssh-agent.exe
app/node_modules/dugite/git/usr/bin/ssh.exe
app/node_modules/dugite/git/usr/bin/tail.exe
app/node_modules/dugite/git/usr/bin/test.exe
app/node_modules/dugite/git/usr/bin/touch.exe
app/node_modules/dugite/git/usr/bin/tr.exe
app/node_modules/dugite/git/usr/bin/true.exe
app/node_modules/dugite/git/usr/bin/uname.exe
app/node_modules/dugite/git/usr/bin/uniq.exe
app/node_modules/dugite/git/usr/bin/wc.exe
app/node_modules/dugite/git/usr/bin/xargs.exe
```

**Pull request merged**
